name: PR Checks

on:
  pull_request:

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run TypeScript typecheck
        run: pnpm typecheck

      - name: Run ESLint
        run: pnpm lint --max-warnings=0

      - name: Run tests
        run: pnpm test

      - name: Check Prettier formatting
        run: pnpm prettier --check "**/*.{ts,tsx,json,css,md}"
